### ISSUE TITLE
Peer Review - Roadmap

### ISSUE THREAD

**Issue by simon-0215** [John-Popovici/duel-of-the-eights#53]
**Artifact Under Review**
Hazard Analysis Report
**Team Number for Team Doing the Review**
Team24
**Description of Issue**
Section8
Include regular checkpoints in the roadmap to revisit the hazard analysis. This could help the team remain proactive as the project progresses, addressing any new hazards that emerge.

**Comment by nigelmoses32** [comment]
Implementing regular checkpoints for hazard analysis may not be practical due to the dynamic nature of non-functional requirements (NFRs), which evolve as the project progresses. Rigidly scheduled checkpoints risk inefficiency, as hazards may no longer be relevant or prematurely analyzed, diverting resources from more immediate tasks. Instead, a context-driven approach—revisiting hazard analysis when specific triggers arise, such as major milestones or system changes—ensures flexibility and relevance without unnecessary overhead.

By avoiding over-specification and focusing on problem-driven iteration, the team can address hazards meaningfully as they emerge. This balanced approach avoids turning checkpoints into routine exercises and ensures that hazard analysis remains aligned with the project’s real-time needs, supporting efficient and adaptive development.
